# Generated by Django 3.1.2 on 2020-10-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_marker', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=500)),
                ('vacancy_link', models.CharField(max_length=500)),
                ('new_or_old', models.BooleanField(default=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.marker')),
            ],
        ),
    ]
