# Generated by Django 3.1.2 on 2020-10-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='vacancy_marker',
        ),
        migrations.AddField(
            model_name='marker',
            name='slug',
            field=models.SlugField(default='Python junior'),
            preserve_default=False,
        ),
    ]
