# Generated by Django 3.1.2 on 2020-10-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20201010_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='new_or_old',
            field=models.CharField(default='New', max_length=3),
        ),
    ]
