# Generated by Django 3.1.2 on 2020-10-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20201010_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='new_or_old',
            field=models.IntegerField(default=0),
        ),
    ]
